### ISSUE TITLE
go mod dependency issue:  invalid pseudo-version: major version without preceding tag must be v0, not v1

### ISSUE THREAD

**Issue by cmoulliard** [appscode/go#45]
### Issue

When my go.mod file is processed, then the following dep issue is reported as the `pongo2` dep relies on a wrong module

```
go: github.com/appscode/go@v0.0.0-20190424183524-60025f1135c9 requires
	github.com/flosch/pongo2@v0.0.0-20181225140029-79872a7b2769 requires
	github.com/go-check/check@v1.0.0-20180628173108-788fd7840127: invalid pseudo-version: major version without preceding tag must be v0, not v1
```

**Comment by tamalsaha** [comment]
Use the master version. I deleted the pongo2 dependency https://github.com/appscode/go/commit/0887d8ec2eccf1bd9e087052e890c5a784e6db72 to fix this.
